module.exports = {
  apps: [
    {
      name: 'kudbee-web',
      script: 'npx',
      args: 'tsx services/ingestion/server.js',
      cwd: '/opt/kudbee',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: '/var/log/kudbee/web-error.log',
      out_file: '/var/log/kudbee/web-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'kudbee-hermes',
      script: 'npx',
      args: 'tsx worker.js',
      cwd: '/opt/kudbee',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
      max_memory_restart: '256M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/var/log/kudbee/hermes-error.log',
      out_file: '/var/log/kudbee/hermes-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'kudbee-monitor',
      script: 'node',
      args: 'services/monitor/agent.js',
      cwd: '/opt/kudbee',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
      max_memory_restart: '256M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/var/log/kudbee/monitor-error.log',
      out_file: '/var/log/kudbee/monitor-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'kudbee-sentinel',
      script: 'npx',
      args: 'tsx services/sentinel/src/index.ts',
      cwd: '/opt/kudbee',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
      max_memory_restart: '256M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/var/log/kudbee/sentinel-error.log',
      out_file: '/var/log/kudbee/sentinel-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
  ],
};
