export type ExecutionStatus = 'queued' | 'approved' | 'rejected' | 'running' | 'completed' | 'failed' | 'cancelled' | 'rolled_back';
export type ApprovalLevel = 'automatic' | 'user' | 'administrator';
export type CommandCategory = 'scan' | 'read' | 'install' | 'build' | 'test' | 'config' | 'deploy' | 'migration' | 'secret' | 'infrastructure' | 'file_write';
export type ExecutionRisk = 'none' | 'low' | 'medium' | 'high' | 'critical';
export interface ExecutionCommand { id: string; description: string; category: CommandCategory; risk: ExecutionRisk; command: string | null; args: string[]; workingDir: string | null; estimatedDurationMs: number | null; requiresApproval: ApprovalLevel; rollbackCommand: string | null; status: ExecutionStatus; output: string | null; exitCode: number | null; startedAt: string | null; completedAt: string | null; retryCount: number; maxRetries: number; agentId: string | null; dependsOn: string[]; }
export interface ExecutionQueue { workspaceId: string; planId: string; commands: ExecutionCommand[]; status: 'idle' | 'running' | 'paused' | 'completed' | 'failed'; currentCommandId: string | null; startedAt: string | null; completedAt: string | null; totalCount: number; completedCount: number; failedCount: number; estimatedTotalMs: number; }
export interface ExecutionResult { commandId: string; status: ExecutionStatus; output: string | null; exitCode: number | null; durationMs: number; startedAt: string; completedAt: string; error: string | null; }
export interface ExecutionSummary { workspaceId: string; totalCommands: number; successful: number; failed: number; cancelled: number; rolledBack: number; totalDurationMs: number; riskSummary: Record<ExecutionRisk, number>; approvalSummary: Record<ApprovalLevel, { requested: number; approved: number; rejected: number }>; modifiedFiles: string[]; errors: string[]; recommendations: string[]; }
export interface ApprovalRequest { id: string; commandId: string; commandDescription: string; level: ApprovalLevel; category: CommandCategory; risk: ExecutionRisk; rollbackAvailable: boolean; reason: string; status: 'pending' | 'approved' | 'rejected'; requestedAt: string; respondedAt: string | null; respondedBy: string | null; }
export interface ExecutionPlan { workspaceId: string; planId: string; generatedAt: string; commands: ExecutionCommand[]; queue: ExecutionQueue; pendingApprovals: ApprovalRequest[]; summary: ExecutionSummary; simulation: boolean; }
export interface Provider<T = unknown> { readonly id: string; readonly name: string; readonly kind: 'source-control' | 'compute' | 'deployment' | 'secrets' | 'ai' | 'package-registry' | 'database' | 'cache'; readonly version: string; validate(): Promise<boolean>; capabilities(): string[]; execute?(command: ExecutionCommand): Promise<ExecutionResult>; rollback?(command: ExecutionCommand): Promise<ExecutionResult>; status(): { healthy: boolean; latency: number | null; lastCheck: string }; }
export interface ProviderConfig { providerId: string; enabled: boolean; priority: number; config: Record<string, string>; }
